---
driver:
  name: ec2
  aws_ssh_key_id: aem-nat
  security_group_ids: [ sg-381dbb40]
  region: eu-west-1
  availability_zone: a
  require_chef_omnibus: 12
  subnet_id: subnet-966cf3e1
  iam_profile_name: aws-opsworks-ec2-role
  instance_type: t2.medium
  associate_public_ip: false
  interface: private
  shared_credentials_profile: as
  image_id: ami-ccbf9ab5 #ami-7d50491b

transport:
  name: sftp
  ssh_key: ~/.ssh/as/aem-nat.pem
  username: ec2-user

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: amazon-linux



suites:
  - name: 3x-chef12-amzn1
    attributes:
      td_agent:
        version: 3.1.1
    driver_config:
      require_chef_omnibus: 12.21.3
      image_id: ami-ccbf9ab5 #ami-7d50491b
    run_list:
      - recipe[td-agent::default]
  - name: 3x-chef12-amzn2
    attributes:
      td_agent:
        version: 3.1.1
    driver_config:
      require_chef_omnibus: 12.21.3
      image_id: ami-921423eb
    run_list:
      - recipe[td-agent::default]
  - name: 2x-chef12-amzn1
    attributes:
      td_agent:
        version: 2.1.1
    driver_config:
      require_chef_omnibus: 12.21.3
      image_id: ami-ccbf9ab5 #ami-7d50491b
    run_list:
      - recipe[td-agent::default]
  - name: 2x-chef12-amzn2
    attributes:
      td_agent:
        version: 2.1.1
    driver_config:
      require_chef_omnibus: 12.21.3
      image_id: ami-921423eb
    run_list:
      - recipe[td-agent::default]
